Repository Ducktrio/yes-app, pull requests merged in 2025-07, with the labels that each got.

#4 Authentication System for Backend Server
  .gitignore
  server/.gitignore
  server/Configurations/JwtSettings.cs
  server/Contracts/RoleContract.cs
  server/Contracts/UserContract.cs
  server/Controllers/UsersController.cs
  server/Data/ApplicationDbContext.cs
  server/Data/database.sqlite
  server/Mappers/RoleMapper.cs
  server/Mappers/UserMapper.cs
  server/Migrations/20250710161653_InitialCreate.Designer.cs
  server/Migrations/20250710161653_InitialCreate.cs
  server/Migrations/ApplicationDbContextModelSnapshot.cs
  server/Program.cs
  server/Repositories/RoleRepository.cs
  server/Repositories/UserRepository.cs
  server/Services/AuthenticationService.cs
  server/Services/RoleService.cs
  server/Services/UserService.cs
  server/Utilities/DatetimeUtility.cs
  server/Validators/RoleValidator.cs
  server/Validators/UserValidator.cs
  server/Yes.csproj
  server/appsettings.example.json
Labels: enhancement

#9 Created all necessary contracts
  server/Contracts/CustomerContract.cs
  server/Contracts/RoomContract.cs
  server/Contracts/RoomTicketContract.cs
  server/Contracts/RoomTypeContract.cs
  server/Contracts/ServiceContract.cs
  server/Contracts/ServiceTicketContract.cs
  server/Yes.csproj
Labels: enhancement

#11 Dev server repositories
  server/Program.cs
  server/Repositories/CustomerRepository.cs
  server/Repositories/RoleRepository.cs
  server/Repositories/RoomRepository.cs
  server/Repositories/RoomTicketRepository.cs
  server/Repositories/RoomTypeRepository.cs
  server/Repositories/ServiceRepository.cs
  server/Repositories/ServiceTicketRepository.cs
  server/Yes.csproj
Labels: enhancement

#13 Added mappers for all models
  server/Mappers/CustomerMapper.cs
  server/Mappers/RoomMapper.cs
  server/Mappers/RoomTicketMapper.cs
  server/Mappers/RoomTypeMapper.cs
  server/Mappers/ServiceMapper.cs
  server/Mappers/ServiceTicketMapper.cs
  server/Yes.csproj
Labels: enhancement

#19 Automatic room update when checkout service ticket closed
  server/Contracts/ServiceTicketContract.cs
  server/Program.cs
  server/Services/ServiceTicketService.cs
  server/Validators/ServiceTicketValidator.cs
Labels: enhancement

#50 Added full_name query for customer
  server/Controllers/CustomersController.cs
  server/Repositories/CustomerRepository.cs
  server/Services/CustomerService.cs
Labels: enhancement

#52 Receptionist panel
  frontend/api/RoomService.ts
  frontend/api/RoomTicketService.ts
  frontend/app/_components/CheckCard.tsx
  frontend/app/_components/RoomCard.tsx
  frontend/app/_components/checkin.tsx
  frontend/app/_components/create-ticket.tsx
  frontend/app/login/page.tsx
  frontend/app/manager/_components/sidebar.tsx
  frontend/app/manager/layout.tsx
  frontend/app/manager/rooms/page.tsx
  frontend/app/manager/tickets/page.tsx
  frontend/app/manager/users/page.tsx
  frontend/app/reception/_components/drawer-list-availables.tsx
  frontend/app/reception/_components/drawer-list-unavailables.tsx
  frontend/app/reception/_components/room-detail.tsx
  frontend/app/reception/_components/room-drawer.tsx
  frontend/app/reception/_components/sidebar.tsx
  frontend/app/reception/checkin/page.tsx
  frontend/app/reception/checkout/page.tsx
  frontend/app/reception/checks/[slug]/page.tsx
  frontend/app/reception/checks/page.tsx
  frontend/app/reception/customer/page.tsx
  frontend/app/reception/layout.tsx
  frontend/app/reception/page.tsx
  frontend/app/reception/rooms/page.tsx
  frontend/app/reception/tickets/page.tsx
  frontend/contexts/AuthContext.tsx
  frontend/hooks/useFetchCustomers.tsx
  frontend/types/Customer.ts
  frontend/types/RoomTicket.ts
  frontend/utils/datatime-unix.ts
  frontend/utils/datetime-timeago.ts
Labels: core

#55 54 error on build for reception release
  frontend/api/RoomService.ts
  frontend/app/_components/create-ticket.tsx
  frontend/app/reception/layout.tsx
  frontend/app/reception/rooms/page.tsx
  frontend/utils/datatime-unix.ts
Labels: bug

#67 Fix buggy auth
  frontend/api/UserService.ts
  frontend/app/login/page.tsx
  frontend/app/manager/_components/sidebar.tsx
  frontend/contexts/AuthContext.tsx
Labels: bug

#68 Release Patch Fixes
  frontend/api/UserService.ts
  frontend/app/login/page.tsx
  frontend/app/manager/_components/sidebar.tsx
  frontend/app/staff/[slug]/page.tsx
  frontend/app/staff/_components/sidebar.tsx
  frontend/contexts/AuthContext.tsx
  server/Controllers/RolesController.cs
  server/Models/RoomTicket.cs
  server/Models/ServiceTicket.cs
  server/Services/RoomTicketService.cs
Labels: bug, core
